version: '3.4'

services:
  rsappfrontend:
    image: rsappfrontend
    build:
      context: rsapp-frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
